name: Pull Request Checks

on: 
  pull_request:
    branches:
      - main
      - develop


jobs:
  pull-request-checks:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18' 

      - name: Install Packages
        run: npm install

      - name: Run Lint  
        run: npm run lint

      - name: Run Typescript compiler  
        run: npx tsc --noEmit

      - name: Run Test  
        run: npm run test